[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/:page.html"
  to = "/:page"
  status = 301

[[redirects]]
  from = "/blog/:slug.html"
  to = "/blog/:slug"
  status = 301

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug.html"
  status = 200
